import type { GunItem } from '@platform/items';

/**
 * The kit the team draws on: a combat pistol, a compact SMG, an assault rifle, a combat shotgun, a bolt-action sniper and
 * a squad LMG. What they do (how they look and sound is each screen's: `client/looks.ts`).
 * Tuned for 100 health, against the hostiles (60 for a rifleman, 220 for a heavy gunner): the rifle kills
 * a rifleman in two or three body shots. Every bullet chips the walls (`carve`): a shot on the same spot goes
 * a little deeper each time, so a wall can be shot open (a firing port) or shot to pieces.
 */
export const WEAPONS: Record<string, GunItem> = {
  pistol: {
    kind: 'gun',
    name: 'Combat Pistol',
    rpm: 420,
    damage: [38, 26],
    falloff: [15, 35],
    headshot: 1.6,
    magazine: 15,
    reserve: 75,
    reload: 1.4,
    spread: { hip: 1.8, aim: 0.3, move: 1, air: 2.5, bloom: 0.5 },
    recoil: { up: 1.4, side: 0.4, recover: 0.85 },
    aim: { zoom: 1.2, time: 0.14, move: 0.85, sight: 'dot' },
    mobility: 1.1,
    carve: { radius: 0.09, depth: 0.04 },
    penetration: { depth: 0.7, damageLoss: 0.45 },
  },
  smg: {
    kind: 'gun',
    name: 'Compact SMG',
    auto: true,
    rpm: 950,
    damage: [24, 14],
    falloff: [10, 26],
    headshot: 1.4,
    magazine: 32,
    reserve: 160,
    reload: 1.7,
    spread: { hip: 2.6, aim: 0.55, move: 0.8, air: 2.4, bloom: 0.18 },
    recoil: { up: 0.5, side: 0.5, recover: 0.8 },
    aim: { zoom: 1.2, time: 0.15, move: 0.8, sight: 'holo' },
    mobility: 1.08,
    carve: { radius: 0.1, depth: 0.025 },
  },
  rifle: {
    kind: 'gun',
    name: 'Assault Rifle',
    auto: true,
    rpm: 640,
    damage: [30, 22],
    falloff: [22, 48],
    headshot: 1.5,
    magazine: 30,
    reserve: 150,
    reload: 2.1,
    spread: { hip: 2.2, aim: 0.12, move: 1.3, air: 3, bloom: 0.22 },
    recoil: { up: 0.85, side: 0.35, recover: 0.7 },
    aim: { zoom: 1.35, time: 0.22, move: 0.62, sight: 'holo' },
    mobility: 0.95,
    carve: { radius: 0.09, depth: 0.04 },
    penetration: { depth: 1.15, damageLoss: 0.32 },
  },
  shotgun: {
    kind: 'gun',
    name: 'Combat Shotgun',
    rpm: 72,
    pellets: 9,
    damage: [15, 4],
    falloff: [6, 18],
    headshot: 1.2,
    magazine: 6,
    reserve: 36,
    reload: 0.48,
    shells: true,
    range: 45,
    spread: { hip: 5.2, aim: 4.2, move: 0.8, air: 1, bloom: 0 },
    recoil: { up: 3.5, side: 1, recover: 0.8 },
    aim: { zoom: 1.15, time: 0.18, move: 0.75, sight: 'holo' },
    action: 'pump',
    carve: { radius: 0.07, depth: 0.01 },
  },
  sniper: {
    kind: 'gun',
    name: 'Bolt-Action Sniper',
    rpm: 46,
    damage: [110, 90],
    falloff: [60, 120],
    headshot: 2,
    magazine: 5,
    reserve: 30,
    reload: 2.6,
    range: 250,
    spread: { hip: 7, aim: 0, move: 5, air: 8, bloom: 0 },
    recoil: { up: 4.5, side: 1, recover: 0.6 },
    aim: { zoom: 4, time: 0.32, move: 0.45, sight: 'scope' },
    action: 'bolt',
    mobility: 0.9,
    carve: { radius: 0.12, depth: 0.42 },
    penetration: { depth: 2.2, damageLoss: 0.18 },
  },
  lmg: {
    kind: 'gun',
    name: 'Squad LMG',
    auto: true,
    rpm: 600,
    damage: [30, 23],
    falloff: [25, 55],
    headshot: 1.4,
    magazine: 100,
    reserve: 300,
    reload: 5,
    range: 170,
    spread: { hip: 3.4, aim: 0.35, move: 1.8, air: 3.5, bloom: 0.12 },
    recoil: { up: 0.7, side: 0.6, recover: 0.6 },
    aim: { zoom: 1.3, time: 0.4, move: 0.45, sight: 'holo', color: '#ff3b30' },
    mobility: 0.84,
    carve: { radius: 0.1, depth: 0.05 },
    penetration: { depth: 1.4, damageLoss: 0.28 },
  },
};
